version: 2.1

orbs:
  python: circleci/python@1.5.0

jobs:
  build:
    docker:
      - image:  circleci/python:3.8
        auth:
          username: polystigmate
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout

      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true

      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t polystigmate/py_docker:$TAG .
          docker login -u $DOCKER_USER -p $DOCKERHUB_PASSWORD
          docker push polystigmate/py_docker:$TAG

  test:
    docker:
      - image: circleci/python:3.8
        auth:
          username: $DOCKER_USER
          password: $DOCKERHUB_PASSWORD
    steps:
      - run: |
          export
          date

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test