apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: web2
  name: web2
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: web2
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: web2
    spec:
      containers:
        - env:
            - name: TEXT
              value: work2
          image: polystigmate/py_docker:0.1.52
          name: web2
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}
